### PR TITLE
minor edits for clarification

### PR DESCRIPTION
**Pull request by chrlaney**
@lwasser Please check some of the text I commented - based on how the comments show up in the preview, I'm not sure how this will appear on your website.

### CODE REVIEW

**Comment by chrlaney** [comment]
Hi Leah,

No problem - I am learning as I go so this is great. Fresh eyes just catch the minor typos. :)
1. Done
2. I assume you mean use a back tick (`) - sorry, I don't use markdown but it seems that's what you use elsewhere. Made this change.
3. Done. So interesting! 
plotRGB(RGBbrick) returns a black box with a few slightly lighter pixels - almost like it's plotting three full RGB plots on top of one another? Not sure.

Let me know if this works for you!

**Comment by lwasser** [comment]
Hey @chrlaney 
try this:
plotRGB(RGBbrick,r=3,g=2,b=1, scale=800, stretch = "Lin")

the images have funny values in them. for instance NA's are 15000. And the data are generally in the 0-3000 ish range. divided by 10000 that's 0-.3 in reflectance world. You can stretch the data using the stretch command and life gets better and prettier. :) let me know how it goes.

**Comment by lwasser** [comment]
Almost there!

DEM$extent should be DEM@extent. test it in R :)

Per your comment in the first file - sure - the earth's surface makes sense. i use that sometimes too. if you think it will be clear to folks, it's more precise. Why don't you remove the comment and make the text change and i can then merge away :)

Thanks @chrlaney !!!

**Comment by chrlaney** [comment]
Done - thanks!

**Comment by lwasser** [comment]
@chrlaney THANK YOU SO MUCH!! look - this is my first official PR being merged. THANKS for all of the great feedback, corrections, etc!!it's all improving the lessons! plus we got a comment today on the raster one :) yay!

**Comment by chrlaney** [comment]
And my second (first was with Claire yesterday!). Nice to have a little bit of time to play with code!

But now the bad news - maybe I messed up a character somewhere? The text lost its formatting after section header "Recommended Pre-Lesson Reading"!

**Comment by lwasser** [comment]
Hmmm – what page doesn’t look right?

**Comment by chrlaney** [comment]
http://neondataskills.org/R/Raster-Data-In-R/

**Comment by lwasser** [comment]
Fixed!
You missed a closing </li>
Easy fix. Glad you caught that!!!

l. ☺

**Comment by lwasser** [comment]
Oh so now I’ve made a change SO you can PR against my repo to your repo to update yours. ☺
Woo hoo git hub!
l.

**Comment by chrlaney** [comment]
Had to read up on that - but it seems to have worked! Cool!

**Comment by lwasser** [comment]
Oh sorry – how confusing am i?

When you have a list in html:

Ul – unordered list (bullets not numbers)
Each bullet needs an <li>text here </li>

The </li> closes the line. In html you pretty much always have to close the tags ☺ you get used to seeing weird things on pages and figuring it’s a missing closing tag.

<ul>
<li>here is a bullet.</li>
</ul>

l. ☺

**Comment by chrlaney** [comment]
Lol - I made the confusing comment, not you! I understood the tag part and I must have accidentally deleted the </li> without realizing it.

I had to read up on how to pull in your changes, because you have the base branch. So I learned to generate a new pull request, but switch the head and the base. Then I was able to accept the pull request and merge your changes into my branch! 

Thanks for the list tutorial though! :)

**Comment by lwasser** [comment]
HAHA – oh goodness. Ok good! yes it’s fun to PR on your own repo and then get to merge your own PR ☺ hehe!

**Pull request merged**
