### PR TITLE
Alterations to lidar lesson

### PR DESCRIPTION
**Pull request by natalie-robinson**
typo fixes, added subsetting the data using base functions instead of dplyr

### CODE REVIEW

**Comment by lwasser** [comment]
hey natalie -- hist(cent_ovr[[2]]) works for me

cent_ovr is a list of lists. so each list within the object is all the pixel values for a plot. so when you run hist(cent_ovr) it doesn't know what to plot whereas [[2]] asks R for the second list (the second plots values) in the object. Did it not run that way for you?

**Comment by lwasser** [comment]
so the second value in the list would be cent_ovr[[2]][2]

**Comment by natalie-robinson** [comment]
No, it didn’t ….  I just got a single list!  I’ll run through it again and see if I get the same behavior.

Natalie Robinson
Quantitative Ecologist- Biostatistician
[NEON_logo]
1685 38th Street Suite 100
Boulder, CO 80301
720-330-1675
nrobinson@neoninc.org<mailto:nrobinson@neoninc.org>

**Comment by lwasser** [comment]
Hmmm – that’s odd behavior.

This line of code, extracts pixels within a buffer for each plot. So it can’t just be one big list or else there would be no way to summarize on the plot level. Is there a different command somewhere to generate cent_ovr OR can you send me the code that’s creating it? maybe there’s a disconnect between my code and the lesson??

cent_ovr <- extract(chm,centroid_sp,buffer = 20)

Thanks!
leah

**Comment by chrlaney** [comment]
I just caught up to this point in the workshop lessons. Here's what I'm running into.

First, we are asked to run this:
`cent_ovr <- extract(chm,centroid_sp,buffer = 20)`

The output is a list of 18 lists (or arrays). So calling `hist(cent_ovr[[2]])` at this point works fine.
But I'm not to that stage yet. 

I'm next asked to run:
`squarePlot <- readShapePoly("CHM_InSitu_Data/PlotCentroid_Shapefile/SJERPlotCentroids_Buffer.shp")`
`cent_ovr <- extract(chm, squarePlot, weights=FALSE, fun=max)`

`cent_ovr` is reassigned to a single matrix (not a list!) of 1 column and 18 rows. So now when I am actually asked to run
`hist(cent_ovr[[2]])`
it no longer works!

**Comment by lwasser** [comment]
AAHhhh -- YES this makes perfect sense.

So maybe we need to reword the text.

in that section, i show them three ways to do the same thing.

If you do the extract method - you get a list of lists. That is because each list represents pixels for the plot. then you have to aggregate to a single value. but it's nic ebecause you can use the hist tool to explore the data- something you'd often want to do!

The second way is to use the shapefile polygons to clip the data. When you do that - it's like doing a focal stats in arcgis. It returns summary stats for the pixels. THEN you get a list of one value for each plot - the max in this case. 

It was NOT my intent to teach all of these - i just wanted to show option1, option2, option 3. i think we should use the extract method in class because it's nice to explore the data.

what do you think i should add to make the OPTIONS more clear :) thanks for catching this @chrlaney and @natalie-robinson 

also note i added a capstone lesson 

http://neondataskills.org/R/create-NDVI-in-R/

it requires a fourth tiff which you can get by redownloading the rasters zip file.

**Comment by chrlaney** [comment]
Yes, I think rewording the text would be helpful. 
Your first two 'options' (actually, let's follow your text and call them 'variations') return objects of different classes. Therefore, you are not showing your users multiple ways to do the same thing - you are showing them how to do similar but ultimately different things.  If you are going to call these 'variations', then the next piece of your tutorial should be able to function on the outputs of any of the three. Does that make sense?
Time for me to switch to some other stuff for the day. This is going great Leah! I am learning a lot!

**Pull request merged**
