### PR TITLE
Merge pull request #1 from lwasser/gh-pages

### PR DESCRIPTION
**Pull request by chrlaney**
pulling lwasser's recent changes

### CODE REVIEW

**Comment by lwasser** [comment]
did this work? it looks like you tried to PR INTO my repo :)

**Comment by chrlaney** [comment]
Not what I meant to do, which is why I closed it.

I was able to pull in your changes last time, but for some reason I am having a hard time doing it again. I can see that your branch is ahead of mine. Are you around?


________________________________

**Comment by lwasser** [comment]
I’m working at home today ☺ so I’m around the neighborhood but not in the office.

So this might help, I found it in the git help. I ALWAYS get this mixed up.

The base branch is where you think changes should be applied, the head branch is what you would like to be applied

So. In your case, do a PR – but the base is YOUR BRANCH. And the head is MY LWASSER branch. See if that works. I can always reject a PR so you can’t mess anything up here. ☺ the beauty of PRs!!! Let me know if that helps / works!
Leah

**Comment by chrlaney** [comment]
Yeah, that's what I did last time. There was a switch branches button, so switching the base and head was easy (I am doing this from the github website). This time, the switch branches button was not available, and when I changed from your branch to my branch as the base, the head branch option disappeared. Finally figured it out but it was not intuitive. The GitHub website in some ways is great, but could use some redesign :). Anyway, my branch should be up to date with yours now.

**Comment by lwasser** [comment]
Yes – it’s funny because EVERYONE that I know really likes git. It’s so powerful. But people have the same feedback that you just gave – if only it were more intuitive….

Glad you figured it out!! ☺
It’s really fun to work collaboratively in this way! I love having more eyes on things because it means more issues get caught!!

Leah

**Pull request closed without merging**
