### PR TITLE
alterations to keep problems from occuring

### PR DESCRIPTION
**Pull request by natalie-robinson**

### CODE REVIEW

**Comment by natalie-robinson** [comment]
Hey Leah - the last HDF5 figure in the 'about' lesson is kinda repetitive and I didn't really see what it was trying to illustrate. Just a thought.

**Comment by natalie-robinson** [comment]
Hey Leah,

    It is easy to miss downloading the hyperspectral data at the beginning of the viewer lesson, can you put that link in a big black box that matches the one for the sensor data?

**Comment by lwasser** [comment]
Hey @natalie-robinson  -- this is great. Can you please do two things for me.

1. please add neondataskills.org back to the CNAME file so it's exactly like mine.
2. can you please remove the comment to me in the text? those items as best resolved as a issue because if i accept your changes, not your comment to me is public to anyone who views the page.

Thank you!

**Comment by lwasser** [comment]
hey @natalie-robinson did you do a

    git pull 

before submtiting this? this file no longer exists in this repo - it's been renamed which makes me think you need to make sure you have the most recent version. I think i made some changes via links, etc. you may end up needing to merge.

If it's easier for us to get together quickly at the end of the day, let me know. i want to accept this but you are missing some changes.. 
leah

**Comment by lwasser** [comment]
ok @natalie-robinson i've incorporated  your edits. I *hope* i've caught them all. please let me know if i missed anything. i'm closing this PR

**Pull request closed without merging**
